services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.0
    environment:
      - discovery.type=single-node  # Single-node setup
      - bootstrap.memory_lock=true  # Prevent memory swapping
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # Set JVM heap size for ElasticSearch
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"  # HTTP API
      - "9300:9300"  # Transport API, 	Node-to-node comms
    volumes:
      - es_data:/usr/share/elasticsearch/data  # Persistent storage for ElasticSearch data

volumes:
  es_data:
    driver: local
